const data = {
  products: [
    {
      _id: "1",
      name: "Nike Slim shirt",
      category: "Shirts",
      image: "/images/p1.jpg",
      price: 120,
      brand: "nike",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countingStock: 100,
    },

    {
      _id: "2",
      name: "Addidas Slim shirt",
      category: "Shirts",
      image: "/images/p2.jpg",
      price: 100,
      brand: "Addidas",
      rating: 4.5,
      numReviews: 10,
      description: "high quality product",
      countingStock: 50,
    },

    {
      _id: "3",
      name: "Lacoste Free shirt",
      category: "Shirts",
      image: "/images/p3.jpg",
      price: 220,
      brand: "Lacoste",
      rating: 4.8,
      numReviews: 17,
      description: "high quality product",
      countingStock: 70,
    },

    {
      _id: "4",
      name: "Nike Slim Pant",
      category: "Pants",
      image: "/images/p4.jpg",
      price: 78,
      brand: "Nike",
      rating: 4.5,
      numReviews: 14,
      description: "high quality product",
      countingStock: 0,
    },
    {
      _id: "5",
      name: "Puma Slim shirt",
      category: "Pants",
      image: "/images/p5.jpg",
      price: 50,
      brand: "Puma",
      rating: 4.2,
      numReviews: 19,
      description: "high quality product",
      countingStock: 12,
    },
    {
      _id: "6",
      name: "Addidas Fit Pant",
      category: "Pants",
      image: "/images/p6.jpg",
      price: 139,
      brand: "Addida",
      rating: 4.5,
      numReviews: 15,
      description: "high quality product",
      countingStock: 78,
    },
  ],
};

export default data;
